### ISSUE TITLE
Incorrect order-dependent import behavior due to Python import caching

### ISSUE THREAD

**Issue by yklcs** [2024-poka-science-war-ai/melee-docker-nightly#2]
https://github.com/2024-poka-science-war-ai/melee-docker-nightly/blob/14872267940928eaa11f850cacaa4f898a5161ef/matchmaking/agent_loader.py#L42-L46

Because Python caches imports, the first loaded module will be imported if agents have the same `agent_module_name`.
This currently occurs with the current example agents, leading to the same agent being used twice.

Note that there is a typo for the second example agent, but fixing this results in the same behavior, which led me to the above conclusion.
https://github.com/2024-poka-science-war-ai/melee-docker-nightly/blob/14872267940928eaa11f850cacaa4f898a5161ef/matchmaking/example_p2/example_agent_config.yaml#L1

**Comment by a-nodi** [comment]
I have changed the two example agent's class name and module name by adding numbers at the end of the name
Also made them print their names to find out they are not the same class imported in the matchmaker.py.

Fixed typo error in match_maker_config.yaml.

Modification has been applied in the branch "Issue#2".

Thanks for the bug report. :)
